icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
idle_bg = "#002b36ff"
info_bg = "#268bd2ff"
good_bg = "#859900ff"
warning_bg = "#b58900ff"
critical_bg = "#dc322fff"
alternating_tint_bg = "#000000ff"
separator = "<span font='12'>\ue0b2</span>"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:100) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"
player = "spotify"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "pacman"
interval = 600
format = " $icon $pacman updates available "
format_singular = " $icon $pacman update available "
format_up_to_date = " $icon "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
[[block.click]]
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs/ | wofi --show dmenu"
[[block.click]]
# Updates the block on right click
button = "right"
update = true

[[block]]
block = "net"
format = " $icon $ip "

[[block]]
block = "time"
interval = 60
[block.format]
#full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "
